name: Deploy to Home Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Go to project
        run: |
          cd ~/apps/home-server-demo
          git pull origin dev

      - name: Install dependencies
        run: |
          cd ~/apps/home-server-demo
          npm ci

      - name: Reload application
        run: |
          pm2 reload home-server-demo

      - name: Health Check
        run: |
          sleep 5
          curl --fail http://localhost:3000/health
